package net.epitap.degeneracycraft.datagen;

import net.epitap.degeneracycraft.Degeneracycraft;
import net.epitap.degeneracycraft.items.DCItems;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.registries.Registries;
import net.minecraft.data.PackOutput;
import net.minecraft.data.tags.ItemTagsProvider;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.common.data.ExistingFileHelper;
import org.jetbrains.annotations.Nullable;

import java.util.concurrent.CompletableFuture;

public class DCItemTagGenerator extends ItemTagsProvider {
    
    public static final TagKey<Item> BAUXITE_MULTIPLIED_ORE_MATERIAL =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"bauxite_multiplied_ore_material"));
    public static final TagKey<Item> BERYL_MULTIPLIED_ORE_MATERIAL =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"beryl_multiplied_ore_material"));
    public static final TagKey<Item> BORAX_MULTIPLIED_ORE_MATERIAL =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"borax_multiplied_ore_material"));
    public static final TagKey<Item> CASSITERITE_MULTIPLIED_ORE_MATERIAL =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"cassiterite_multiplied_ore_material"));
    public static final TagKey<Item> CHROMITE_MULTIPLIED_ORE_MATERIAL =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"chromite_multiplied_ore_material"));
    public static final TagKey<Item> FLUORITE_MULTIPLIED_ORE_MATERIAL =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"cassiterite_multiplied_ore_material"));
    public static final TagKey<Item> GRAPHITE_MULTIPLIED_ORE_MATERIAL =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"graphite_multiplied_ore_material"));
    public static final TagKey<Item> IRON_MULTIPLIED_ORE_MATERIAL =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"iron_multiplied_ore_material"));
    public static final TagKey<Item> LATERITE_MULTIPLIED_ORE_MATERIAL =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"laterite_multiplied_ore_material"));
    public static final TagKey<Item> LIMESTONE_MULTIPLIED_ORE_MATERIAL =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"limestone_multiplied_ore_material"));
    public static final TagKey<Item> NITRATINE_MULTIPLIED_ORE_MATERIAL =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"nitratine_multiplied_ore_material"));
    public static final TagKey<Item> PEGMATITE_MULTIPLIED_ORE_MATERIAL =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"pegmatite_multiplied_ore_material"));
    public static final TagKey<Item> PENTLANDITE_MULTIPLIED_ORE_MATERIAL =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"pentlandite_multiplied_ore_material"));
    public static final TagKey<Item> PHOSPHORITE_MULTIPLIED_ORE_MATERIAL =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"phosphorite_multiplied_ore_material"));
    public static final TagKey<Item> PYRITE_MULTIPLIED_ORE_MATERIAL = TagKey.create(Registries.ITEM, new ResourceLocation(Degeneracycraft.MOD_ID, "pyrite_multiplied_ore_material"));
    public static final TagKey<Item> PYROLUSITE_MULTIPLIED_ORE_MATERIAL = TagKey.create(Registries.ITEM, new ResourceLocation(Degeneracycraft.MOD_ID, "pyrolusite_multiplied_ore_material"));
    public static final TagKey<Item> QUARTZ_MULTIPLIED_ORE_MATERIAL = TagKey.create(Registries.ITEM, new ResourceLocation(Degeneracycraft.MOD_ID, "quartz_multiplied_ore_material"));
    public static final TagKey<Item> RUTILE_MULTIPLIED_ORE_MATERIAL = TagKey.create(Registries.ITEM, new ResourceLocation(Degeneracycraft.MOD_ID, "rutile_multiplied_ore_material"));
    public static final TagKey<Item> SPODUMENE_MULTIPLIED_ORE_MATERIAL =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"spodumene_multiplied_ore_material"));
    public static final TagKey<Item> SYLVITE_MULTIPLIED_ORE_MATERIAL =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"sylvite_multiplied_ore_material"));
    public static final TagKey<Item> ULEXITE_MULTIPLIED_ORE_MATERIAL =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"ulexite_multiplied_ore_material"));
    public static final TagKey<Item> VANADINITE_MULTIPLIED_ORE_MATERIAL =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"vanadinite_multiplied_ore_material"));

    public static final TagKey<Item> ELEMENT_ITEMS =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"element_items"));
    public static final TagKey<Item> SUBSTANCE_ITEMS =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"substance_items"));

    public static final TagKey<Item> COPPER_MACHINE_ELEMENTS =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"copper_machine_elements"));
    public static final TagKey<Item> GOLD_MACHINE_ELEMENTS =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"gold_machine_elements"));
    public static final TagKey<Item> IRON_MACHINE_ELEMENTS =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"iron_machine_elements"));
    public static final TagKey<Item> TIN_MACHINE_ELEMENTS =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"tin_machine_elements"));

    public static final TagKey<Item> BASIC_ASTRONOMY_MACHINE_PARTS =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"basic_astronomy_machine_parts"));
    public static final TagKey<Item> BASIC_BIOLOGY_MACHINE_PARTS =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"basic_biology_machine_parts"));
    public static final TagKey<Item> BASIC_CHEMISTRY_MACHINE_PARTS =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"basic_chemistry_machine_parts"));
    public static final TagKey<Item> BASIC_DYNAMIC_ENERGETICS_MACHINE_PARTS =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"basic_dynamic_energetics_machine_parts"));
    public static final TagKey<Item> BASIC_ENGINEERING_MACHINE_PARTS =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"basic_engineering_machine_parts"));
    public static final TagKey<Item> BASIC_FORMAL_SCIENCE_MACHINE_PARTS =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"basic_formal_science_machine_parts"));
    public static final TagKey<Item> BASIC_GEO_SCIENCE_MACHINE_PARTS =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"basic_geo_science_machine_parts"));
    public static final TagKey<Item> BASIC_HYBRID_PHYSICS_MACHINE_PARTS =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"basic_hybrid_physics_machine_parts"));
    public static final TagKey<Item> BASIC_IMITATION_MAGIC_ENGINEERING_MACHINE_PARTS =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"basic_imitation_magic_engineering_machine_parts"));
    public static final TagKey<Item> BASIC_JENITH_VOID_SCIENCE_MACHINE_PARTS =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"basic_jenith_void_science_machine_parts"));
    public static final TagKey<Item> BASIC_KALEIDOSCOPIC_REALITY_SCIENCE_MACHINE_PARTS =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"basic_kaleidoscopic_reality_science_machine_parts"));

    public static final TagKey<Item> BASIC_MACHINE_CIRCUIT_PARTS =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"basic_machine_circuit_parts"));



    public static final TagKey<Item> TEST_ITEMS =TagKey.create(Registries.ITEM,new ResourceLocation(Degeneracycraft.MOD_ID,"test_items"));

    public DCItemTagGenerator(PackOutput packOutput, CompletableFuture<HolderLookup.Provider> future,
                               CompletableFuture<TagLookup<Block>> completableFuture, @Nullable ExistingFileHelper existingFileHelper) {
        super(packOutput, future, completableFuture, Degeneracycraft.MOD_ID, existingFileHelper);
    }

    @Override
    protected void addTags(HolderLookup.Provider pProvider) {
        // Add Item Tags here
        tag(BERYL_MULTIPLIED_ORE_MATERIAL)
                .add(DCItems.RAW_BERYL_ORE.get())
                .add(DCItems.BERYL_DUST.get())
                .add(DCItems.BERYL_PUREDUST.get())
                .add(DCItems.BERYL_LEACHATE.get())
                .add(DCItems.BERYL_CONCENTRATE.get())
                .add(DCItems.BERYL_PLASMA.get())
                .add(DCItems.BERYL_DEGENERATEMATTER.get())
                .add(DCItems.BERYL_SOUP.get())
                .add(DCItems.BERYL_IMAGINARYMATTER.get())
                .add(DCItems.STABLE_BERYL_IMAGINARYMATTER.get())
                .add(DCItems.BERYL_TACHYON.get())
                .add(DCItems.BERYL_ANTIMATTER.get())
                .add(DCItems.BERYL_ULTRAHOTPLASMA.get())
                .add(DCItems.BERYL_OVERFLUID.get())
                .add(DCItems.BERYL_CRYSTAL.get())
                .add(DCItems.BERYL_PRECIPITATE.get())
                .add(DCItems.BERYL_WASHEDDUST.get())
                .add(DCItems.BERYL_ORESINTER.get())
                .add(DCItems.BERYL_INGOT.get());
        //
        tag(BORAX_MULTIPLIED_ORE_MATERIAL)
                .add(DCItems.RAW_BORAX_ORE.get())
                .add(DCItems.BORAX_DUST.get())
                .add(DCItems.BORAX_PUREDUST.get())
                .add(DCItems.BORAX_LEACHATE.get())
                .add(DCItems.BORAX_CONCENTRATE.get())
                .add(DCItems.BORAX_PLASMA.get())
                .add(DCItems.BORAX_DEGENERATEMATTER.get())
                .add(DCItems.BORAX_SOUP.get())
                .add(DCItems.BORAX_IMAGINARYMATTER.get())
                .add(DCItems.STABLE_BORAX_IMAGINARYMATTER.get())
                .add(DCItems.BORAX_TACHYON.get())
                .add(DCItems.BORAX_ANTIMATTER.get())
                .add(DCItems.BORAX_ULTRAHOTPLASMA.get())
                .add(DCItems.BORAX_OVERFLUID.get())
                .add(DCItems.BORAX_CRYSTAL.get())
                .add(DCItems.BORAX_PRECIPITATE.get())
                .add(DCItems.BORAX_WASHEDDUST.get())
                .add(DCItems.BORAX_ORESINTER.get())
                .add(DCItems.BORAX_INGOT.get());
        //
        tag(BAUXITE_MULTIPLIED_ORE_MATERIAL)
                .add(DCItems.RAW_BAUXITE_ORE.get())
                .add(DCItems.BAUXITE_DUST.get())
                .add(DCItems.BAUXITE_PUREDUST.get())
                .add(DCItems.BAUXITE_LEACHATE.get())
                .add(DCItems.BAUXITE_CONCENTRATE.get())
                .add(DCItems.BAUXITE_PLASMA.get())
                .add(DCItems.BAUXITE_DEGENERATEMATTER.get())
                .add(DCItems.BAUXITE_SOUP.get())
                .add(DCItems.BAUXITE_IMAGINARYMATTER.get())
                .add(DCItems.STABLE_BAUXITE_IMAGINARYMATTER.get())
                .add(DCItems.BAUXITE_TACHYON.get())
                .add(DCItems.BAUXITE_ANTIMATTER.get())
                .add(DCItems.BAUXITE_ULTRAHOTPLASMA.get())
                .add(DCItems.BAUXITE_OVERFLUID.get())
                .add(DCItems.BAUXITE_CRYSTAL.get())
                .add(DCItems.BAUXITE_PRECIPITATE.get())
                .add(DCItems.BAUXITE_WASHEDDUST.get())
                .add(DCItems.BAUXITE_ORESINTER.get())
                .add(DCItems.BAUXITE_INGOT.get());
        //
        tag(CASSITERITE_MULTIPLIED_ORE_MATERIAL)
                .add(DCItems.RAW_CASSITERITE_ORE.get())
                .add(DCItems.CASSITERITE_DUST.get())
                .add(DCItems.CASSITERITE_PUREDUST.get())
                .add(DCItems.CASSITERITE_LEACHATE.get())
                .add(DCItems.CASSITERITE_CONCENTRATE.get())
                .add(DCItems.CASSITERITE_PLASMA.get())
                .add(DCItems.CASSITERITE_DEGENERATEMATTER.get())
                .add(DCItems.CASSITERITE_SOUP.get())
                .add(DCItems.CASSITERITE_IMAGINARYMATTER.get())
                .add(DCItems.STABLE_CASSITERITE_IMAGINARYMATTER.get())
                .add(DCItems.CASSITERITE_TACHYON.get())
                .add(DCItems.CASSITERITE_ANTIMATTER.get())
                .add(DCItems.CASSITERITE_ULTRAHOTPLASMA.get())
                .add(DCItems.CASSITERITE_OVERFLUID.get())
                .add(DCItems.CASSITERITE_CRYSTAL.get())
                .add(DCItems.CASSITERITE_PRECIPITATE.get())
                .add(DCItems.CASSITERITE_WASHEDDUST.get())
                .add(DCItems.CASSITERITE_ORESINTER.get())
                .add(DCItems.CASSITERITE_INGOT.get());
        //
        tag(CHROMITE_MULTIPLIED_ORE_MATERIAL)
                .add(DCItems.RAW_CHROMITE_ORE.get())
                .add(DCItems.CHROMITE_DUST.get())
                .add(DCItems.CHROMITE_PUREDUST.get())
                .add(DCItems.CHROMITE_LEACHATE.get())
                .add(DCItems.CHROMITE_CONCENTRATE.get())
                .add(DCItems.CHROMITE_PLASMA.get())
                .add(DCItems.CHROMITE_DEGENERATEMATTER.get())
                .add(DCItems.CHROMITE_SOUP.get())
                .add(DCItems.CHROMITE_IMAGINARYMATTER.get())
                .add(DCItems.STABLE_CHROMITE_IMAGINARYMATTER.get())
                .add(DCItems.CHROMITE_TACHYON.get())
                .add(DCItems.CHROMITE_ANTIMATTER.get())
                .add(DCItems.CHROMITE_ULTRAHOTPLASMA.get())
                .add(DCItems.CHROMITE_OVERFLUID.get())
                .add(DCItems.CHROMITE_CRYSTAL.get())
                .add(DCItems.CHROMITE_PRECIPITATE.get())
                .add(DCItems.CHROMITE_WASHEDDUST.get())
                .add(DCItems.CHROMITE_ORESINTER.get())
                .add(DCItems.CHROMITE_INGOT.get());
        //
        tag(FLUORITE_MULTIPLIED_ORE_MATERIAL)
                .add(DCItems.RAW_FLUORITE_ORE.get())
                .add(DCItems.FLUORITE_DUST.get())
                .add(DCItems.FLUORITE_PUREDUST.get())
                .add(DCItems.FLUORITE_LEACHATE.get())
                .add(DCItems.FLUORITE_CONCENTRATE.get())
                .add(DCItems.FLUORITE_PLASMA.get())
                .add(DCItems.FLUORITE_DEGENERATEMATTER.get())
                .add(DCItems.FLUORITE_SOUP.get())
                .add(DCItems.FLUORITE_IMAGINARYMATTER.get())
                .add(DCItems.STABLE_FLUORITE_IMAGINARYMATTER.get())
                .add(DCItems.FLUORITE_TACHYON.get())
                .add(DCItems.FLUORITE_ANTIMATTER.get())
                .add(DCItems.FLUORITE_ULTRAHOTPLASMA.get())
                .add(DCItems.FLUORITE_OVERFLUID.get())
                .add(DCItems.FLUORITE_CRYSTAL.get())
                .add(DCItems.FLUORITE_PRECIPITATE.get())
                .add(DCItems.FLUORITE_WASHEDDUST.get())
                .add(DCItems.FLUORITE_ORESINTER.get())
                .add(DCItems.FLUORITE_INGOT.get());
        //
        tag(GRAPHITE_MULTIPLIED_ORE_MATERIAL)
                .add(DCItems.RAW_GRAPHITE_ORE.get())
                .add(DCItems.GRAPHITE_DUST.get())
                .add(DCItems.GRAPHITE_PUREDUST.get())
                .add(DCItems.GRAPHITE_LEACHATE.get())
                .add(DCItems.GRAPHITE_CONCENTRATE.get())
                .add(DCItems.GRAPHITE_PLASMA.get())
                .add(DCItems.GRAPHITE_DEGENERATEMATTER.get())
                .add(DCItems.GRAPHITE_SOUP.get())
                .add(DCItems.GRAPHITE_IMAGINARYMATTER.get())
                .add(DCItems.STABLE_GRAPHITE_IMAGINARYMATTER.get())
                .add(DCItems.GRAPHITE_TACHYON.get())
                .add(DCItems.GRAPHITE_ANTIMATTER.get())
                .add(DCItems.GRAPHITE_ULTRAHOTPLASMA.get())
                .add(DCItems.GRAPHITE_OVERFLUID.get())
                .add(DCItems.GRAPHITE_CRYSTAL.get())
                .add(DCItems.GRAPHITE_PRECIPITATE.get())
                .add(DCItems.GRAPHITE_WASHEDDUST.get())
                .add(DCItems.GRAPHITE_ORESINTER.get())
                .add(DCItems.GRAPHITE_INGOT.get());
        //
//            tag(IRON_MULTIPLIED_ORE_MATERIAL)
//                    .add(DCItems.IRON_DUST.get())
//                    .add(DCItems.IRON_PUREDUST.get())
//                    .add(DCItems.IRON_LEACHATE.get())
//                    .add(DCItems.IRON_CONCENTRATE.get())
//                    .add(DCItems.IRON_PLASMA.get())
//                    .add(DCItems.IRON_DEGENERATEMATTER.get())
//                    .add(DCItems.IRON_SOUP.get())
//                    .add(DCItems.IRON_IMAGINARYMATTER.get())
//                    .add(DCItems.STABLE_IRON_IMAGINARYMATTER.get())
//                    .add(DCItems.IRON_TACHYON.get())
//                    .add(DCItems.IRON_ANTIMATTER.get())
//                    .add(DCItems.IRON_ULTRAHOTPLASMA.get())
//                    .add(DCItems.IRON_OVERFLUID.get())
//                    .add(DCItems.IRON_CRYSTAL.get())
//                    .add(DCItems.IRON_PRECIPITATE.get())
//                    .add(DCItems.IRON_WASHEDDUST.get())
//                    .add(DCItems.IRON_ORESINTER.get());
        //
        tag(LATERITE_MULTIPLIED_ORE_MATERIAL)
                .add(DCItems.RAW_LATERITE_ORE.get())
                .add(DCItems.LATERITE_DUST.get())
                .add(DCItems.LATERITE_PUREDUST.get())
                .add(DCItems.LATERITE_LEACHATE.get())
                .add(DCItems.LATERITE_CONCENTRATE.get())
                .add(DCItems.LATERITE_PLASMA.get())
                .add(DCItems.LATERITE_DEGENERATEMATTER.get())
                .add(DCItems.LATERITE_SOUP.get())
                .add(DCItems.LATERITE_IMAGINARYMATTER.get())
                .add(DCItems.STABLE_LATERITE_IMAGINARYMATTER.get())
                .add(DCItems.LATERITE_TACHYON.get())
                .add(DCItems.LATERITE_ANTIMATTER.get())
                .add(DCItems.LATERITE_ULTRAHOTPLASMA.get())
                .add(DCItems.LATERITE_OVERFLUID.get())
                .add(DCItems.LATERITE_CRYSTAL.get())
                .add(DCItems.LATERITE_PRECIPITATE.get())
                .add(DCItems.LATERITE_WASHEDDUST.get())
                .add(DCItems.LATERITE_ORESINTER.get())
                .add(DCItems.LATERITE_INGOT.get());
        //
        tag(LIMESTONE_MULTIPLIED_ORE_MATERIAL)
                .add(DCItems.RAW_LIMESTONE_ORE.get())
                .add(DCItems.LIMESTONE_DUST.get())
                .add(DCItems.LIMESTONE_PUREDUST.get())
                .add(DCItems.LIMESTONE_LEACHATE.get())
                .add(DCItems.LIMESTONE_CONCENTRATE.get())
                .add(DCItems.LIMESTONE_PLASMA.get())
                .add(DCItems.LIMESTONE_DEGENERATEMATTER.get())
                .add(DCItems.LIMESTONE_SOUP.get())
                .add(DCItems.LIMESTONE_IMAGINARYMATTER.get())
                .add(DCItems.STABLE_LIMESTONE_IMAGINARYMATTER.get())
                .add(DCItems.LIMESTONE_TACHYON.get())
                .add(DCItems.LIMESTONE_ANTIMATTER.get())
                .add(DCItems.LIMESTONE_ULTRAHOTPLASMA.get())
                .add(DCItems.LIMESTONE_OVERFLUID.get())
                .add(DCItems.LIMESTONE_CRYSTAL.get())
                .add(DCItems.LIMESTONE_PRECIPITATE.get())
                .add(DCItems.LIMESTONE_WASHEDDUST.get())
                .add(DCItems.LIMESTONE_ORESINTER.get())
                .add(DCItems.LIMESTONE_INGOT.get());
        //
        tag(NITRATINE_MULTIPLIED_ORE_MATERIAL)
                .add(DCItems.RAW_NITRATINE_ORE.get())
                .add(DCItems.NITRATINE_DUST.get())
                .add(DCItems.NITRATINE_PUREDUST.get())
                .add(DCItems.NITRATINE_LEACHATE.get())
                .add(DCItems.NITRATINE_CONCENTRATE.get())
                .add(DCItems.NITRATINE_PLASMA.get())
                .add(DCItems.NITRATINE_DEGENERATEMATTER.get())
                .add(DCItems.NITRATINE_SOUP.get())
                .add(DCItems.NITRATINE_IMAGINARYMATTER.get())
                .add(DCItems.STABLE_NITRATINE_IMAGINARYMATTER.get())
                .add(DCItems.NITRATINE_TACHYON.get())
                .add(DCItems.NITRATINE_ANTIMATTER.get())
                .add(DCItems.NITRATINE_ULTRAHOTPLASMA.get())
                .add(DCItems.NITRATINE_OVERFLUID.get())
                .add(DCItems.NITRATINE_CRYSTAL.get())
                .add(DCItems.NITRATINE_PRECIPITATE.get())
                .add(DCItems.NITRATINE_WASHEDDUST.get())
                .add(DCItems.NITRATINE_ORESINTER.get())
                .add(DCItems.NITRATINE_INGOT.get());
        //
        tag(PEGMATITE_MULTIPLIED_ORE_MATERIAL)
                .add(DCItems.RAW_PEGMATITE_ORE.get())
                .add(DCItems.PEGMATITE_DUST.get())
                .add(DCItems.PEGMATITE_PUREDUST.get())
                .add(DCItems.PEGMATITE_LEACHATE.get())
                .add(DCItems.PEGMATITE_CONCENTRATE.get())
                .add(DCItems.PEGMATITE_PLASMA.get())
                .add(DCItems.PEGMATITE_DEGENERATEMATTER.get())
                .add(DCItems.PEGMATITE_SOUP.get())
                .add(DCItems.PEGMATITE_IMAGINARYMATTER.get())
                .add(DCItems.STABLE_PEGMATITE_IMAGINARYMATTER.get())
                .add(DCItems.PEGMATITE_TACHYON.get())
                .add(DCItems.PEGMATITE_ANTIMATTER.get())
                .add(DCItems.PEGMATITE_ULTRAHOTPLASMA.get())
                .add(DCItems.PEGMATITE_OVERFLUID.get())
                .add(DCItems.PEGMATITE_CRYSTAL.get())
                .add(DCItems.PEGMATITE_PRECIPITATE.get())
                .add(DCItems.PEGMATITE_WASHEDDUST.get())
                .add(DCItems.PEGMATITE_ORESINTER.get())
                .add(DCItems.PEGMATITE_INGOT.get());
        //
        tag(PENTLANDITE_MULTIPLIED_ORE_MATERIAL)
                .add(DCItems.RAW_PENTLANDITE_ORE.get())
                .add(DCItems.PENTLANDITE_DUST.get())
                .add(DCItems.PENTLANDITE_PUREDUST.get())
                .add(DCItems.PENTLANDITE_LEACHATE.get())
                .add(DCItems.PENTLANDITE_CONCENTRATE.get())
                .add(DCItems.PENTLANDITE_PLASMA.get())
                .add(DCItems.PENTLANDITE_DEGENERATEMATTER.get())
                .add(DCItems.PENTLANDITE_SOUP.get())
                .add(DCItems.PENTLANDITE_IMAGINARYMATTER.get())
                .add(DCItems.STABLE_PENTLANDITE_IMAGINARYMATTER.get())
                .add(DCItems.PENTLANDITE_TACHYON.get())
                .add(DCItems.PENTLANDITE_ANTIMATTER.get())
                .add(DCItems.PENTLANDITE_ULTRAHOTPLASMA.get())
                .add(DCItems.PENTLANDITE_OVERFLUID.get())
                .add(DCItems.PENTLANDITE_CRYSTAL.get())
                .add(DCItems.PENTLANDITE_PRECIPITATE.get())
                .add(DCItems.PENTLANDITE_WASHEDDUST.get())
                .add(DCItems.PENTLANDITE_ORESINTER.get())
                .add(DCItems.PENTLANDITE_INGOT.get());
        //
        tag(PHOSPHORITE_MULTIPLIED_ORE_MATERIAL)
                .add(DCItems.RAW_PHOSPHORITE_ORE.get())
                .add(DCItems.PHOSPHORITE_DUST.get())
                .add(DCItems.PHOSPHORITE_PUREDUST.get())
                .add(DCItems.PHOSPHORITE_LEACHATE.get())
                .add(DCItems.PHOSPHORITE_CONCENTRATE.get())
                .add(DCItems.PHOSPHORITE_PLASMA.get())
                .add(DCItems.PHOSPHORITE_DEGENERATEMATTER.get())
                .add(DCItems.PHOSPHORITE_SOUP.get())
                .add(DCItems.PHOSPHORITE_IMAGINARYMATTER.get())
                .add(DCItems.STABLE_PHOSPHORITE_IMAGINARYMATTER.get())
                .add(DCItems.PHOSPHORITE_TACHYON.get())
                .add(DCItems.PHOSPHORITE_ANTIMATTER.get())
                .add(DCItems.PHOSPHORITE_ULTRAHOTPLASMA.get())
                .add(DCItems.PHOSPHORITE_OVERFLUID.get())
                .add(DCItems.PHOSPHORITE_CRYSTAL.get())
                .add(DCItems.PHOSPHORITE_PRECIPITATE.get())
                .add(DCItems.PHOSPHORITE_WASHEDDUST.get())
                .add(DCItems.PHOSPHORITE_ORESINTER.get())
                .add(DCItems.PHOSPHORITE_INGOT.get());
        tag(PYRITE_MULTIPLIED_ORE_MATERIAL)
                .add(DCItems.RAW_PYRITE_ORE.get())
                .add(DCItems.PYRITE_DUST.get())
                .add(DCItems.PYRITE_PUREDUST.get())
                .add(DCItems.PYRITE_LEACHATE.get())
                .add(DCItems.PYRITE_CONCENTRATE.get())
                .add(DCItems.PYRITE_PLASMA.get())
                .add(DCItems.PYRITE_DEGENERATEMATTER.get())
                .add(DCItems.PYRITE_SOUP.get())
                .add(DCItems.PYRITE_IMAGINARYMATTER.get())
                .add(DCItems.STABLE_PYRITE_IMAGINARYMATTER.get())
                .add(DCItems.PYRITE_TACHYON.get())
                .add(DCItems.PYRITE_ANTIMATTER.get())
                .add(DCItems.PYRITE_ULTRAHOTPLASMA.get())
                .add(DCItems.PYRITE_OVERFLUID.get())
                .add(DCItems.PYRITE_CRYSTAL.get())
                .add(DCItems.PYRITE_PRECIPITATE.get())
                .add(DCItems.PYRITE_WASHEDDUST.get())
                .add(DCItems.PYRITE_ORESINTER.get())
                .add(DCItems.PYRITE_INGOT.get());
        //
        tag(PYROLUSITE_MULTIPLIED_ORE_MATERIAL)
                .add(DCItems.RAW_PYROLUSITE_ORE.get())
                .add(DCItems.PYROLUSITE_DUST.get())
                .add(DCItems.PYROLUSITE_PUREDUST.get())
                .add(DCItems.PYROLUSITE_LEACHATE.get())
                .add(DCItems.PYROLUSITE_CONCENTRATE.get())
                .add(DCItems.PYROLUSITE_PLASMA.get())
                .add(DCItems.PYROLUSITE_DEGENERATEMATTER.get())
                .add(DCItems.PYROLUSITE_SOUP.get())
                .add(DCItems.PYROLUSITE_IMAGINARYMATTER.get())
                .add(DCItems.STABLE_PYROLUSITE_IMAGINARYMATTER.get())
                .add(DCItems.PYROLUSITE_TACHYON.get())
                .add(DCItems.PYROLUSITE_ANTIMATTER.get())
                .add(DCItems.PYROLUSITE_ULTRAHOTPLASMA.get())
                .add(DCItems.PYROLUSITE_OVERFLUID.get())
                .add(DCItems.PYROLUSITE_CRYSTAL.get())
                .add(DCItems.PYROLUSITE_PRECIPITATE.get())
                .add(DCItems.PYROLUSITE_WASHEDDUST.get())
                .add(DCItems.PYROLUSITE_ORESINTER.get())
                .add(DCItems.PYROLUSITE_INGOT.get());
        //
        tag(QUARTZ_MULTIPLIED_ORE_MATERIAL)
                .add(DCItems.RAW_QUARTZ_ORE.get())
                .add(DCItems.QUARTZ_DUST.get())
                .add(DCItems.QUARTZ_PUREDUST.get())
                .add(DCItems.QUARTZ_LEACHATE.get())
                .add(DCItems.QUARTZ_CONCENTRATE.get())
                .add(DCItems.QUARTZ_PLASMA.get())
                .add(DCItems.QUARTZ_DEGENERATEMATTER.get())
                .add(DCItems.QUARTZ_SOUP.get())
                .add(DCItems.QUARTZ_IMAGINARYMATTER.get())
                .add(DCItems.STABLE_QUARTZ_IMAGINARYMATTER.get())
                .add(DCItems.QUARTZ_TACHYON.get())
                .add(DCItems.QUARTZ_ANTIMATTER.get())
                .add(DCItems.QUARTZ_ULTRAHOTPLASMA.get())
                .add(DCItems.QUARTZ_OVERFLUID.get())
                .add(DCItems.QUARTZ_CRYSTAL.get())
                .add(DCItems.QUARTZ_PRECIPITATE.get())
                .add(DCItems.QUARTZ_WASHEDDUST.get())
                .add(DCItems.QUARTZ_ORESINTER.get())
                .add(DCItems.QUARTZ_INGOT.get());
        //
        tag(RUTILE_MULTIPLIED_ORE_MATERIAL)
                .add(DCItems.RAW_RUTILE_ORE.get())
                .add(DCItems.RUTILE_DUST.get())
                .add(DCItems.RUTILE_PUREDUST.get())
                .add(DCItems.RUTILE_LEACHATE.get())
                .add(DCItems.RUTILE_CONCENTRATE.get())
                .add(DCItems.RUTILE_PLASMA.get())
                .add(DCItems.RUTILE_DEGENERATEMATTER.get())
                .add(DCItems.RUTILE_SOUP.get())
                .add(DCItems.RUTILE_IMAGINARYMATTER.get())
                .add(DCItems.STABLE_RUTILE_IMAGINARYMATTER.get())
                .add(DCItems.RUTILE_TACHYON.get())
                .add(DCItems.RUTILE_ANTIMATTER.get())
                .add(DCItems.RUTILE_ULTRAHOTPLASMA.get())
                .add(DCItems.RUTILE_OVERFLUID.get())
                .add(DCItems.RUTILE_CRYSTAL.get())
                .add(DCItems.RUTILE_PRECIPITATE.get())
                .add(DCItems.RUTILE_WASHEDDUST.get())
                .add(DCItems.RUTILE_ORESINTER.get())
                .add(DCItems.RUTILE_INGOT.get());
        //
        tag(SPODUMENE_MULTIPLIED_ORE_MATERIAL)
                .add(DCItems.RAW_SPODUMENE_ORE.get())
                .add(DCItems.SPODUMENE_DUST.get())
                .add(DCItems.SPODUMENE_PUREDUST.get())
                .add(DCItems.SPODUMENE_LEACHATE.get())
                .add(DCItems.SPODUMENE_CONCENTRATE.get())
                .add(DCItems.SPODUMENE_PLASMA.get())
                .add(DCItems.SPODUMENE_DEGENERATEMATTER.get())
                .add(DCItems.SPODUMENE_SOUP.get())
                .add(DCItems.SPODUMENE_IMAGINARYMATTER.get())
                .add(DCItems.STABLE_SPODUMENE_IMAGINARYMATTER.get())
                .add(DCItems.SPODUMENE_TACHYON.get())
                .add(DCItems.SPODUMENE_ANTIMATTER.get())
                .add(DCItems.SPODUMENE_ULTRAHOTPLASMA.get())
                .add(DCItems.SPODUMENE_OVERFLUID.get())
                .add(DCItems.SPODUMENE_CRYSTAL.get())
                .add(DCItems.SPODUMENE_PRECIPITATE.get())
                .add(DCItems.SPODUMENE_WASHEDDUST.get())
                .add(DCItems.SPODUMENE_ORESINTER.get())
                .add(DCItems.SPODUMENE_INGOT.get());
        //
        tag(SYLVITE_MULTIPLIED_ORE_MATERIAL)
                .add(DCItems.RAW_SYLVITE_ORE.get())
                .add(DCItems.SYLVITE_DUST.get())
                .add(DCItems.SYLVITE_PUREDUST.get())
                .add(DCItems.SYLVITE_LEACHATE.get())
                .add(DCItems.SYLVITE_CONCENTRATE.get())
                .add(DCItems.SYLVITE_PLASMA.get())
                .add(DCItems.SYLVITE_DEGENERATEMATTER.get())
                .add(DCItems.SYLVITE_SOUP.get())
                .add(DCItems.SYLVITE_IMAGINARYMATTER.get())
                .add(DCItems.STABLE_SYLVITE_IMAGINARYMATTER.get())
                .add(DCItems.SYLVITE_TACHYON.get())
                .add(DCItems.SYLVITE_ANTIMATTER.get())
                .add(DCItems.SYLVITE_ULTRAHOTPLASMA.get())
                .add(DCItems.SYLVITE_OVERFLUID.get())
                .add(DCItems.SYLVITE_CRYSTAL.get())
                .add(DCItems.SYLVITE_PRECIPITATE.get())
                .add(DCItems.SYLVITE_WASHEDDUST.get())
                .add(DCItems.SYLVITE_ORESINTER.get())
                .add(DCItems.SYLVITE_INGOT.get());
        //
        tag(ULEXITE_MULTIPLIED_ORE_MATERIAL)
                .add(DCItems.RAW_ULEXITE_ORE.get())
                .add(DCItems.ULEXITE_DUST.get())
                .add(DCItems.ULEXITE_PUREDUST.get())
                .add(DCItems.ULEXITE_LEACHATE.get())
                .add(DCItems.ULEXITE_CONCENTRATE.get())
                .add(DCItems.ULEXITE_PLASMA.get())
                .add(DCItems.ULEXITE_DEGENERATEMATTER.get())
                .add(DCItems.ULEXITE_SOUP.get())
                .add(DCItems.ULEXITE_IMAGINARYMATTER.get())
                .add(DCItems.STABLE_ULEXITE_IMAGINARYMATTER.get())
                .add(DCItems.ULEXITE_TACHYON.get())
                .add(DCItems.ULEXITE_ANTIMATTER.get())
                .add(DCItems.ULEXITE_ULTRAHOTPLASMA.get())
                .add(DCItems.ULEXITE_OVERFLUID.get())
                .add(DCItems.ULEXITE_CRYSTAL.get())
                .add(DCItems.ULEXITE_PRECIPITATE.get())
                .add(DCItems.ULEXITE_WASHEDDUST.get())
                .add(DCItems.ULEXITE_ORESINTER.get())
                .add(DCItems.ULEXITE_INGOT.get());
        //
        tag(VANADINITE_MULTIPLIED_ORE_MATERIAL)
                .add(DCItems.RAW_VANADINITE_ORE.get())
                .add(DCItems.VANADINITE_DUST.get())
                .add(DCItems.VANADINITE_PUREDUST.get())
                .add(DCItems.VANADINITE_LEACHATE.get())
                .add(DCItems.VANADINITE_CONCENTRATE.get())
                .add(DCItems.VANADINITE_PLASMA.get())
                .add(DCItems.VANADINITE_DEGENERATEMATTER.get())
                .add(DCItems.VANADINITE_SOUP.get())
                .add(DCItems.VANADINITE_IMAGINARYMATTER.get())
                .add(DCItems.STABLE_VANADINITE_IMAGINARYMATTER.get())
                .add(DCItems.VANADINITE_TACHYON.get())
                .add(DCItems.VANADINITE_ANTIMATTER.get())
                .add(DCItems.VANADINITE_ULTRAHOTPLASMA.get())
                .add(DCItems.VANADINITE_OVERFLUID.get())
                .add(DCItems.VANADINITE_CRYSTAL.get())
                .add(DCItems.VANADINITE_PRECIPITATE.get())
                .add(DCItems.VANADINITE_WASHEDDUST.get())
                .add(DCItems.VANADINITE_ORESINTER.get())
                .add(DCItems.VANADINITE_INGOT.get());

        tag(ELEMENT_ITEMS)
                .add(DCItems.CHLORINE_GAS.get())
                .add(DCItems.HYDROGEN_GAS.get())
                .add(DCItems.OXYGEN_GAS.get())
                .add(DCItems.SILICON_INGOT.get())
                .add(DCItems.SILICON_NUGGET.get())
                .add(DCItems.TIN_INGOT.get())
                .add(DCItems.TIN_NUGGET.get())
                ;

        tag(SUBSTANCE_ITEMS)
                .add(DCItems.EMPTY_CONTAINER.get())
                .add(DCItems.WATER_CONTAINER.get())
                .add(DCItems.AMMONIA_GAS.get())
                .add(DCItems.AMMONIUM_SULFATE_DUST.get())
                .add(DCItems.AMMONIUM_HYDROGEN_SULFATE_DUST.get())
                .add(DCItems.FERRIC_OXIDE_DUST.get())
                .add(DCItems.IRON_DISULFIDE_DUST.get())
                .add(DCItems.HYDROCHLORIC_ACID_SOLUTION.get())
                .add(DCItems.HYDROGEN_CHLORIDE_GAS.get())
                .add(DCItems.HYDROGEN_PEROXIDE_SOLUTION.get())
                .add(DCItems.POTASSIUM_CHLORIDE_DUST.get())
                .add(DCItems.POTASSIUM_NITRATE_DUST.get())
                .add(DCItems.SODIUM_CHLORIDE_DUST.get())
                .add(DCItems.SODIUM_NITRATE_DUST.get())
                .add(DCItems.SULFUR_DIOXIDE_GAS.get())
                .add(DCItems.SULFURIC_ACID_SOLUTION.get())
                ;
        tag(COPPER_MACHINE_ELEMENTS)
                .add(DCItems.COPPER_BEARING.get())
                .add(DCItems.COPPER_BOLT.get())
                .add(DCItems.COPPER_CAM.get())
                .add(DCItems.COPPER_CHAIN.get())
                .add(DCItems.COPPER_GEAR.get())
                .add(DCItems.COPPER_JOINT.get())
                .add(DCItems.COPPER_KEY.get())
                .add(DCItems.COPPER_NUT.get())
                .add(DCItems.COPPER_PIPE.get())
                .add(DCItems.COPPER_PIPEJOINT.get())
                .add(DCItems.COPPER_PLATE.get())
                .add(DCItems.COPPER_RIVET.get())
                .add(DCItems.COPPER_ROD.get())
                .add(DCItems.COPPER_SHAFT.get())
                .add(DCItems.COPPER_SHAFTCOUPLING.get())
                .add(DCItems.COPPER_SPRING.get())
                .add(DCItems.COPPER_SHAPESTEEL.get())
                .add(DCItems.COPPER_WIRE.get());
        tag(GOLD_MACHINE_ELEMENTS)
                .add(DCItems.GOLD_BEARING.get())
                .add(DCItems.GOLD_BOLT.get())
                .add(DCItems.GOLD_CAM.get())
                .add(DCItems.GOLD_CHAIN.get())
                .add(DCItems.GOLD_GEAR.get())
                .add(DCItems.GOLD_JOINT.get())
                .add(DCItems.GOLD_KEY.get())
                .add(DCItems.GOLD_NUT.get())
                .add(DCItems.GOLD_PIPE.get())
                .add(DCItems.GOLD_PIPEJOINT.get())
                .add(DCItems.GOLD_PLATE.get())
                .add(DCItems.GOLD_RIVET.get())
                .add(DCItems.GOLD_ROD.get())
                .add(DCItems.GOLD_SHAFT.get())
                .add(DCItems.GOLD_SHAFTCOUPLING.get())
                .add(DCItems.GOLD_SPRING.get())
                .add(DCItems.GOLD_SHAPESTEEL.get())
                .add(DCItems.GOLD_WIRE.get());
        tag(IRON_MACHINE_ELEMENTS)
                .add(DCItems.IRON_BEARING.get())
                .add(DCItems.IRON_BOLT.get())
                .add(DCItems.IRON_CAM.get())
                .add(DCItems.IRON_CHAIN.get())
                .add(DCItems.IRON_GEAR.get())
                .add(DCItems.IRON_JOINT.get())
                .add(DCItems.IRON_KEY.get())
                .add(DCItems.IRON_NUT.get())
                .add(DCItems.IRON_PIPE.get())
                .add(DCItems.IRON_PIPEJOINT.get())
                .add(DCItems.IRON_PLATE.get())
                .add(DCItems.IRON_RIVET.get())
                .add(DCItems.IRON_ROD.get())
                .add(DCItems.IRON_SHAFT.get())
                .add(DCItems.IRON_SHAFTCOUPLING.get())
                .add(DCItems.IRON_SPRING.get())
                .add(DCItems.IRON_SHAPESTEEL.get())
                .add(DCItems.IRON_WIRE.get());
        tag(TIN_MACHINE_ELEMENTS)
                .add(DCItems.TIN_BEARING.get())
                .add(DCItems.TIN_BOLT.get())
                .add(DCItems.TIN_CAM.get())
                .add(DCItems.TIN_CHAIN.get())
                .add(DCItems.TIN_GEAR.get())
                .add(DCItems.TIN_JOINT.get())
                .add(DCItems.TIN_KEY.get())
                .add(DCItems.TIN_NUT.get())
                .add(DCItems.TIN_PIPE.get())
                .add(DCItems.TIN_PIPEJOINT.get())
                .add(DCItems.TIN_PLATE.get())
                .add(DCItems.TIN_RIVET.get())
                .add(DCItems.TIN_ROD.get())
                .add(DCItems.TIN_SHAFT.get())
                .add(DCItems.TIN_SHAFTCOUPLING.get())
                .add(DCItems.TIN_SPRING.get())
                .add(DCItems.TIN_SHAPESTEEL.get())
                .add(DCItems.TIN_WIRE.get());
        tag(BASIC_ASTRONOMY_MACHINE_PARTS)
                .add(DCItems.SIMPLE_CONCAVE_LENS.get())
                .add(DCItems.SIMPLE_CONVEX_LENS.get())
                ;
        tag(BASIC_BIOLOGY_MACHINE_PARTS)
                .add(DCItems.SIMPLE_BIOLOGICAL_FIBER.get())
                ;
        tag(BASIC_CHEMISTRY_MACHINE_PARTS)
                .add(DCItems.SIMPLE_CHEMICAL_CONTAINER.get())
                .add(DCItems.SIMPLE_CRYSTALLIZATION_SUBSTRATE_PLATE.get())
                .add(DCItems.SIMPLE_LIQUID_NEUTRALIZATION_PROCESSOR.get())
                .add(DCItems.SIMPLE_TEMPERED_GLASS.get())
                .add(DCItems.SIMPLE_ORE_SORTING_FILTER.get())
                ;
        tag(BASIC_DYNAMIC_ENERGETICS_MACHINE_PARTS)
                ;
        tag(BASIC_ENGINEERING_MACHINE_PARTS)
                .add(DCItems.BASIC_CIRCUIT.get())
                .add(DCItems.BASIC_COMBINEDSHAFT.get())
                .add(DCItems.BASIC_CONDENSER.get())
                .add(DCItems.BASIC_CONDUCTOR_WIRE.get())
                .add(DCItems.BASIC_CONVEYORBELT.get())
                .add(DCItems.BASIC_CYLINDER.get())
                .add(DCItems.BASIC_DIODE.get())
                .add(DCItems.BASIC_DRIVECHAIN.get())
                .add(DCItems.BASIC_EQUIPMENT_CONTAINER.get())
                .add(DCItems.BASIC_FIXED_FRAME.get())
                .add(DCItems.BASIC_INSCRIBE_NEEDLE.get())
                .add(DCItems.BASIC_INSCRIBED_CIRCUIT.get())
                .add(DCItems.BASIC_LINKAGE.get())
                .add(DCItems.BASIC_MACHINE_SCREEN.get())
                .add(DCItems.BASIC_MOTOR.get())
                .add(DCItems.BASIC_PIPE_BUNDLE.get())
                .add(DCItems.BASIC_PROCESSING_BASE.get())
                .add(DCItems.BASIC_REDSTONE_BATTERY.get())
                .add(DCItems.BASIC_REINFORCED_PLATE.get())
                .add(DCItems.BASIC_ROBOT_ARM.get())
                .add(DCItems.BASIC_TRANSISTOR.get())
                .add(DCItems.BASIC_TURBINE.get())
                .add(DCItems.BASIC_ASTRONOMY_CIRCUIT.get())
                .add(DCItems.BASIC_BIOLOGY_CIRCUIT.get())
                .add(DCItems.BASIC_CHEMISTRY_CIRCUIT.get())
                .add(DCItems.BASIC_DYNAMIC_ENERGETICS_CIRCUIT.get())
                .add(DCItems.BASIC_ENGINEERING_CIRCUIT.get())
                .add(DCItems.BASIC_FORMAL_SCIENCE_CIRCUIT.get())
                .add(DCItems.BASIC_GEO_SCIENCE_CIRCUIT.get())
                .add(DCItems.BASIC_HYBRID_PHYSICS_CIRCUIT.get())
                .add(DCItems.BASIC_IMITATION_MAGIC_ENGINEERING_CIRCUIT.get());
        tag(BASIC_FORMAL_SCIENCE_MACHINE_PARTS)
                .add(DCItems.SIMPLE_ASTRONOMY_MEMORY_CIRCUIT.get())
                .add(DCItems.SIMPLE_BIOLOGY_MEMORY_CIRCUIT.get())
                .add(DCItems.SIMPLE_CHEMISTRY_MEMORY_CIRCUIT.get())
                .add(DCItems.SIMPLE_DYNAMIC_ENERGETICS_MEMORY_CIRCUIT.get())
                .add(DCItems.SIMPLE_ENGINEERING_MEMORY_CIRCUIT.get())
                .add(DCItems.SIMPLE_FORMAL_SCIENCE_MEMORY_CIRCUIT.get())
                .add(DCItems.SIMPLE_GEO_SCIENCE_MEMORY_CIRCUIT.get())
                .add(DCItems.SIMPLE_HYBRID_PHYSICS_MEMORY_CIRCUIT.get())
                .add(DCItems.SIMPLE_IMITATION_MAGIC_ENGINEERING_MEMORY_CIRCUIT.get())
                .add(DCItems.SIMPLE_PROCESSING_CIRCUIT.get());
        tag(BASIC_MACHINE_CIRCUIT_PARTS)
                .add(DCItems.BASIC_PERFORMANCE_ASTRONOMICAL_TELESCOPE_CIRCUIT.get())
                .add(DCItems.BASIC_PERFORMANCE_STARLIGHT_COLLECTOR_CIRCUIT.get())
                .add(DCItems.BASIC_PERFORMANCE_FINE_PARTICLE_ADSORBER_CIRCUIT.get())
                .add(DCItems.BASIC_PERFORMANCE_BIO_REACTOR_CIRCUIT.get())
                .add(DCItems.BASIC_PERFORMANCE_CELL_INCUBATOR_CIRCUIT.get())
                .add(DCItems.BASIC_PERFORMANCE_CROP_CULTIVATOR_CIRCUIT.get())
                .add(DCItems.BASIC_PERFORMANCE_CHEMICAL_REACTOR_CIRCUIT.get())
                .add(DCItems.BASIC_PERFORMANCE_COMPOUND_PURIFIER_CIRCUIT.get())
                .add(DCItems.BASIC_PERFORMANCE_ELECTROLYSER_CIRCUIT.get())
                .add(DCItems.BASIC_POWER_STEAM_GENERATOR_CIRCUIT.get())
                .add(DCItems.BASIC_TECHNOLOGY_COMPRESSION_CONDENSER_CIRCUIT.get())
                .add(DCItems.BASIC_TECHNOLOGY_ELECTROMAGNETIC_INDUCTOR_CIRCUIT.get())
                .add(DCItems.BASIC_TECHNOLOGY_MACHINE_MANUFACTURER_CIRCUIT.get())
                .add(DCItems.BASIC_TECHNOLOGY_MACHINE_ELEMENT_PROCESSOR_CIRCUIT.get())
                .add(DCItems.BASIC_TECHNOLOGY_MACHINE_PART_PROCESSOR_CIRCUIT.get())
                .add(DCItems.BASIC_TECHNOLOGY_MULTIBLOCK_EQUIPMENT_FABRICATOR_CIRCUIT.get())
                .add(DCItems.BASIC_PERFORMANCE_CIRCUIT_BUILDER_CIRCUIT.get())
                .add(DCItems.BASIC_PERFORMANCE_MACHINE_DATA_INSTALLER_CIRCUIT.get())
                .add(DCItems.BASIC_PERFORMANCE_DESIGNATED_DATA_INJECTOR_CIRCUIT.get())
                .add(DCItems.BASIC_PERFORMANCE_ORE_SORTER_CIRCUIT.get())
                .add(DCItems.BASIC_PERFORMANCE_ROCK_CRASHER_CIRCUIT.get())
                .add(DCItems.BASIC_PERFORMANCE_SOIL_PURIFIER_CIRCUIT.get())
                .add(DCItems.BASIC_PERFORMANCE_ELECTRIC_ARC_FURNACE_CIRCUIT.get())
                .add(DCItems.BASIC_PERFORMANCE_FORMING_MACHINE_CIRCUIT.get())
                .add(DCItems.BASIC_PERFORMANCE_MATERIAL_SEPARATOR_CIRCUIT.get())
                .add(DCItems.BASIC_TECHNOLOGY_IMITATION_MAGIC_ENGRAVER_CIRCUIT.get())
                .add(DCItems.BASIC_TECHNOLOGY_SUSPECTED_MAGIC_CONDENSER_CIRCUIT.get())
                .add(DCItems.BASIC_TECHNOLOGY_VIRTUAL_SIGIL_PROCESSOR_CIRCUIT.get())
                .add(DCItems.BASIC_TECHNOLOGY_VOID_WORLD_COORDINATE_RECORDING_MACHINE_CIRCUIT.get())
                .add(DCItems.BASIC_PERFORMANCE_REALITY_PHASE_ADJUSTMENT_MACHINE_CIRCUIT.get())

        ;
        tag(BASIC_GEO_SCIENCE_MACHINE_PARTS)
        ;
        tag(BASIC_HYBRID_PHYSICS_MACHINE_PARTS)
        ;
        tag(BASIC_IMITATION_MAGIC_ENGINEERING_MACHINE_PARTS)
                .add(DCItems.SIMPLE_PSEUDO_MAGIC_THUNDER_CRYSTAL.get())
                .add(DCItems.SIMPLE_PSEUDO_MAGIC_WIND_CRYSTAL.get())
                .add(DCItems.SIMPLE_PSEUDO_MAGIC_WATER_CRYSTAL.get())
                .add(DCItems.SIMPLE_PSEUDO_MAGIC_NIL_CRYSTAL.get())
                .add(DCItems.SIMPLE_PSEUDO_MAGIC_DARK_CRYSTAL.get())
                .add(DCItems.SIMPLE_PSEUDO_MAGIC_ICE_CRYSTAL.get())
                .add(DCItems.SIMPLE_PSEUDO_MAGIC_EARTH_CRYSTAL.get())
                .add(DCItems.SIMPLE_PSEUDO_MAGIC_FIRE_CRYSTAL.get())
                .add(DCItems.SIMPLE_PSEUDO_MAGIC_LIGHT_CRYSTAL.get())
        ;
        tag(BASIC_JENITH_VOID_SCIENCE_MACHINE_PARTS)
        ;
        tag(BASIC_KALEIDOSCOPIC_REALITY_SCIENCE_MACHINE_PARTS)
        ;
    }

    @Override
    public String getName() {
        return "Item Tags";
    }

//    private static TagKey<Item> tag(String name){
//        return ItemTags.create(new ResourceLocation(Degeneracycraft.MOD_ID,name));
//    }
}